export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-surface": "#e0e2ed",
        "surface-dim": "#10131b",
        "error": "#ffb4ab",
        "on-secondary-container": "#c4abff",
        "on-tertiary-fixed": "#351000",
        "inverse-on-surface": "#2d3039",
        "secondary-container": "#571bc1",
        "surface-container-lowest": "#0b0e16",
        "on-tertiary": "#571e00",
        "surface-container": "#1c2028",
        "surface-container-low": "#181c23",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#c1c6d7",
        "on-secondary-fixed-variant": "#5516be",
        "on-primary-fixed": "#001a41",
        "primary": "#adc6ff",
        "secondary-fixed": "#e9ddff",
        "on-tertiary-fixed-variant": "#7c2e00",
        "tertiary-fixed-dim": "#ffb595",
        "on-secondary-fixed": "#23005c",
        "surface-container-high": "#272a32",
        "secondary": "#d0bcff",
        "tertiary": "#ffb595",
        "outline": "#8b90a0",
        "surface": "#10131b",
        "on-primary-fixed-variant": "#004493",
        "inverse-primary": "#005bc1",
        "outline-variant": "#414755",
        "primary-fixed-dim": "#adc6ff",
        "background": "#10131b",
        "on-error": "#690005",
        "tertiary-container": "#ef6719",
        "primary-container": "#4b8eff",
        "tertiary-fixed": "#ffdbcc",
        "surface-tint": "#adc6ff",
        "on-primary-container": "#00285c",
        "on-tertiary-container": "#4c1a00",
        "secondary-fixed-dim": "#d0bcff",
        "on-background": "#e0e2ed",
        "on-primary": "#002e69",
        "surface-container-highest": "#31353d",
        "on-secondary": "#3c0091",
        "error-container": "#93000a",
        "surface-bright": "#363942",
        "inverse-surface": "#e0e2ed",
        "primary-fixed": "#d8e2ff",
        "surface-variant": "#31353d"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "lg": "24px",
        "unit": "4px",
        "gutter": "16px",
        "xs": "4px",
        "xl": "40px",
        "margin-page": "32px",
        "md": "16px",
        "sm": "8px"
      },
      "fontFamily": {
        "h2": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "h1": ["Inter"],
        "display": ["Inter"],
        "body-md": ["Inter"],
        "code": ["monospace"]
      },
      "fontSize": {
        "h2": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
        "h1": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "display": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "code": ["13px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
